using Homespun.Features.AgentOrchestration.Services;
using Microsoft.AspNetCore.Mvc;

namespace Homespun.Features.AgentOrchestration.Controllers;

/// <summary>
/// API endpoints for agent orchestration features.
/// </summary>
[ApiController]
[Route("api/orchestration")]
[Produces("application/json")]
public class OrchestrationController(
    IBranchIdGeneratorService branchIdGeneratorService) : ControllerBase
{
    /// <summary>
    /// Generate a working branch ID from an issue title using AI.
    /// </summary>
    /// <param name="request">The request containing the issue title</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>The generated branch ID</returns>
    [HttpPost("generate-branch-id")]
    [ProducesResponseType<GenerateBranchIdResponse>(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<GenerateBranchIdResponse>> GenerateBranchId(
        [FromBody] GenerateBranchIdRequest request,
        CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(request.Title))
        {
            return BadRequest(new GenerateBranchIdResponse(
                Success: false,
                BranchId: null,
                Error: "Title is required",
                WasAiGenerated: false));
        }

        var result = await branchIdGeneratorService.GenerateAsync(request.Title, cancellationToken);

        return Ok(new GenerateBranchIdResponse(
            Success: result.Success,
            BranchId: result.BranchId,
            Error: result.Error,
            WasAiGenerated: result.WasAiGenerated));
    }
}

/// <summary>
/// Request model for generating a branch ID.
/// </summary>
/// <param name="Title">The issue title to generate a branch ID from</param>
public record GenerateBranchIdRequest(string Title);

/// <summary>
/// Response model for branch ID generation.
/// </summary>
/// <param name="Success">Whether the generation succeeded</param>
/// <param name="BranchId">The generated branch ID if successful</param>
/// <param name="Error">Error message if failed</param>
/// <param name="WasAiGenerated">Whether the branch ID was generated by AI or fell back to sanitization</param>
public record GenerateBranchIdResponse(
    bool Success,
    string? BranchId,
    string? Error,
    bool WasAiGenerated);
