namespace Homespun.Shared.Models.Plans;

/// <summary>
/// Represents information about a plan file generated by Claude Code.
/// </summary>
public class PlanFileInfo
{
    /// <summary>
    /// The name of the plan file (e.g., "fluffy-aurora.md").
    /// </summary>
    public required string FileName { get; init; }

    /// <summary>
    /// The full path to the plan file.
    /// </summary>
    public required string FilePath { get; init; }

    /// <summary>
    /// The last modified date of the plan file.
    /// </summary>
    public required DateTime LastModified { get; init; }

    /// <summary>
    /// The size of the file in bytes.
    /// </summary>
    public long FileSizeBytes { get; init; }

    /// <summary>
    /// A preview of the plan content (first 3 lines).
    /// </summary>
    public string? Preview { get; init; }
}
