namespace Homespun.Features.AgentOrchestration.Services;

/// <summary>
/// Result of a branch ID generation request.
/// </summary>
/// <param name="Success">Whether the generation succeeded</param>
/// <param name="BranchId">The generated branch ID if successful</param>
/// <param name="Error">Error message if failed</param>
/// <param name="WasAiGenerated">Whether the branch ID was generated by AI or fell back to sanitization</param>
public record BranchIdResult(
    bool Success,
    string? BranchId,
    string? Error,
    bool WasAiGenerated = true);

/// <summary>
/// Service for generating working branch IDs from issue titles using AI.
/// </summary>
public interface IBranchIdGeneratorService
{
    /// <summary>
    /// Generates a working branch ID from an issue title using AI.
    /// </summary>
    /// <param name="title">The issue title</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>Generated branch ID (2-4 lowercase hyphen-separated words)</returns>
    Task<BranchIdResult> GenerateAsync(string title, CancellationToken cancellationToken = default);
}
