using Homespun.Shared.Models.Fleece;
using Homespun.Shared.Models.Notifications;

namespace Homespun.Shared.Hubs;

/// <summary>
/// Defines server-to-client SignalR messages for the Notification hub.
/// </summary>
public interface INotificationHubClient
{
    Task NotificationAdded(NotificationDto notification);
    Task NotificationDismissed(string notificationId);

    /// <summary>
    /// Notifies clients when issues are changed (created, updated, deleted) in a project.
    /// </summary>
    Task IssuesChanged(string projectId, IssueChangeType changeType, string issueId);

    /// <summary>
    /// Notifies clients of a structure-preserving field patch on a single issue.
    /// The client applies <paramref name="patch"/> in place via
    /// <c>queryClient.setQueryData</c>; no HTTP refetch is required.
    /// Gated by <c>TaskGraphSnapshot:PatchPush:Enabled</c> on the server.
    /// </summary>
    Task IssueFieldsPatched(string projectId, string issueId, IssueFieldPatch patch);

    /// <summary>
    /// Notifies clients when a branch ID has been successfully generated for an issue.
    /// </summary>
    /// <param name="issueId">The ID of the issue.</param>
    /// <param name="projectId">The ID of the project.</param>
    /// <param name="branchId">The generated branch ID.</param>
    /// <param name="wasAiGenerated">Whether the branch ID was generated by AI or fell back to sanitization.</param>
    Task BranchIdGenerated(string issueId, string projectId, string branchId, bool wasAiGenerated);

    /// <summary>
    /// Notifies clients when branch ID generation fails for an issue.
    /// </summary>
    /// <param name="issueId">The ID of the issue.</param>
    /// <param name="projectId">The ID of the project.</param>
    /// <param name="error">The error message.</param>
    Task BranchIdGenerationFailed(string issueId, string projectId, string error);

    /// <summary>
    /// Notifies clients when an agent is starting for an issue.
    /// </summary>
    /// <param name="issueId">The ID of the issue.</param>
    /// <param name="projectId">The ID of the project.</param>
    /// <param name="branchName">The branch name being used.</param>
    Task AgentStarting(string issueId, string projectId, string branchName);

    /// <summary>
    /// Notifies clients when agent startup fails for an issue.
    /// </summary>
    /// <param name="issueId">The ID of the issue.</param>
    /// <param name="projectId">The ID of the project.</param>
    /// <param name="error">The error message.</param>
    Task AgentStartFailed(string issueId, string projectId, string error);
}
