using Homespun.Shared.Models.Fleece;
using Homespun.Shared.Models.Notifications;

namespace Homespun.Shared.Hubs;

/// <summary>
/// Defines server-to-client SignalR messages for the Notification hub.
/// </summary>
public interface INotificationHubClient
{
    Task NotificationAdded(NotificationDto notification);
    Task NotificationDismissed(string notificationId);

    /// <summary>
    /// Unified per-issue mutation event. Carries the canonical post-mutation
    /// issue body on create / update; <paramref name="issue"/> is <c>null</c>
    /// on delete. <paramref name="issueId"/> may be <c>null</c> for bulk
    /// events (e.g. fleece-sync, clone lifecycle) — clients treat a null id
    /// as "invalidate every issue cache for this project".
    /// </summary>
    Task IssueChanged(string projectId, IssueChangeType kind, string? issueId, IssueResponse? issue);

    /// <summary>
    /// Notifies clients when a branch ID has been successfully generated for an issue.
    /// </summary>
    /// <param name="issueId">The ID of the issue.</param>
    /// <param name="projectId">The ID of the project.</param>
    /// <param name="branchId">The generated branch ID.</param>
    /// <param name="wasAiGenerated">Whether the branch ID was generated by AI or fell back to sanitization.</param>
    Task BranchIdGenerated(string issueId, string projectId, string branchId, bool wasAiGenerated);

    /// <summary>
    /// Notifies clients when branch ID generation fails for an issue.
    /// </summary>
    /// <param name="issueId">The ID of the issue.</param>
    /// <param name="projectId">The ID of the project.</param>
    /// <param name="error">The error message.</param>
    Task BranchIdGenerationFailed(string issueId, string projectId, string error);

    /// <summary>
    /// Notifies clients when an agent is starting for an issue.
    /// </summary>
    /// <param name="issueId">The ID of the issue.</param>
    /// <param name="projectId">The ID of the project.</param>
    /// <param name="branchName">The branch name being used.</param>
    Task AgentStarting(string issueId, string projectId, string branchName);

    /// <summary>
    /// Notifies clients when agent startup fails for an issue.
    /// </summary>
    /// <param name="issueId">The ID of the issue.</param>
    /// <param name="projectId">The ID of the project.</param>
    /// <param name="error">The error message.</param>
    Task AgentStartFailed(string issueId, string projectId, string error);
}
