#!/bin/bash
set -e

# ============================================================================
# Komodo Installation Script
# ============================================================================
#
# This script installs Komodo on an Ubuntu machine with MongoDB.
# Komodo is a container management and deployment system.
#
# Usage:
#   ./scripts/install-komodo.sh
#
# Prerequisites:
#   - Docker installed and running
#   - sudo access
#
# What this script does:
#   1. Creates /etc/komodo directory structure
#   2. Downloads Komodo Docker Compose files
#   3. Generates secure secrets (passkey, JWT, webhook)
#   4. Configures GitHub Container Registry access
#   5. Creates environment file with configuration
#
# After installation:
#   - Run ./scripts/run-komodo.sh to start Komodo
#   - Access Komodo at https://<tailscale-hostname>:3500
#
# Environment Variables (optional):
#   HSP_GITHUB_TOKEN    - GitHub token for GHCR access
#   GITHUB_TOKEN        - Alternative GitHub token variable
#   KOMODO_ADMIN_USER   - Initial admin username (default: admin)
#   KOMODO_ADMIN_PASS   - Initial admin password (auto-generated if not set)

# Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${CYAN}$1${NC}"; }
log_success() { echo -e "${GREEN}$1${NC}"; }
log_warn() { echo -e "${YELLOW}$1${NC}"; }
log_error() { echo -e "${RED}$1${NC}"; }

# Generate a random string for secrets
generate_secret() {
    openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
}

echo
log_info "=== Komodo Installation Script ==="
echo

# Get script directory and repository root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Configuration
KOMODO_DIR="/etc/komodo"
KOMODO_CONFIG_DIR="$REPO_ROOT/config/komodo"

# Step 1: Validate Docker
log_info "[1/5] Checking prerequisites..."

if ! docker version >/dev/null 2>&1; then
    log_error "Docker is not installed or not running."
    log_error "Please install Docker: https://docs.docker.com/engine/install/ubuntu/"
    exit 1
fi
log_success "      Docker is available."

if ! command -v openssl &>/dev/null; then
    log_error "openssl is required for secret generation."
    log_error "Install with: sudo apt-get install openssl"
    exit 1
fi
log_success "      openssl is available."

# Step 2: Create directory structure
log_info "[2/5] Creating directory structure..."

sudo mkdir -p "$KOMODO_DIR"
sudo mkdir -p "$KOMODO_DIR/backups"
sudo mkdir -p "$KOMODO_DIR/docker"
sudo mkdir -p "$KOMODO_DIR/stacks"
sudo mkdir -p "$KOMODO_DIR/repos"
sudo chmod 755 "$KOMODO_DIR"

log_success "      Created $KOMODO_DIR"

# Step 3: Set up GitHub Container Registry access
log_info "[3/5] Configuring GitHub Container Registry..."

# Get GitHub token from environment
GITHUB_TOKEN="${HSP_GITHUB_TOKEN:-${GITHUB_TOKEN:-}}"

# Try reading from ~/.homespun/env if not set
if [ -z "$GITHUB_TOKEN" ]; then
    HOMESPUN_ENV_FILE="$HOME/.homespun/env"
    if [ -f "$HOMESPUN_ENV_FILE" ]; then
        source "$HOMESPUN_ENV_FILE"
        GITHUB_TOKEN="${HSP_GITHUB_TOKEN:-${GITHUB_TOKEN:-}}"
    fi
fi

if [ -z "$GITHUB_TOKEN" ]; then
    log_warn "      No GitHub token found."
    log_warn "      Set GITHUB_TOKEN or HSP_GITHUB_TOKEN for GHCR access."
    log_warn "      Komodo will not be able to pull private images."
else
    # Create Docker config for GHCR
    GHCR_AUTH=$(echo -n "homespun:$GITHUB_TOKEN" | base64)
    sudo tee "$KOMODO_DIR/docker/config.json" > /dev/null << EOF
{
  "auths": {
    "ghcr.io": {
      "auth": "$GHCR_AUTH"
    }
  }
}
EOF
    sudo chmod 600 "$KOMODO_DIR/docker/config.json"
    log_success "      Configured GHCR authentication."
fi

# Step 4: Generate secrets and environment file
log_info "[4/5] Generating configuration..."

# Generate secrets
KOMODO_PASSKEY=$(generate_secret)
KOMODO_JWT_SECRET=$(generate_secret)
KOMODO_WEBHOOK_SECRET=$(generate_secret)
MONGO_PASSWORD=$(generate_secret)

# Admin credentials
ADMIN_USER="${KOMODO_ADMIN_USER:-admin}"
if [ -z "$KOMODO_ADMIN_PASS" ]; then
    ADMIN_PASS=$(generate_secret | head -c 16)
    log_warn "      Generated admin password: $ADMIN_PASS"
    log_warn "      Save this password! It will not be shown again."
else
    ADMIN_PASS="$KOMODO_ADMIN_PASS"
fi

# Create environment file
sudo tee "$KOMODO_DIR/compose.env" > /dev/null << EOF
# Komodo Configuration
# Generated by install-komodo.sh on $(date)

# ============================================================================
# Compose Settings
# ============================================================================
COMPOSE_KOMODO_IMAGE_TAG=latest
COMPOSE_KOMODO_BACKUPS_PATH=$KOMODO_DIR/backups

# ============================================================================
# Database Credentials
# ============================================================================
KOMODO_DB_USERNAME=komodo
KOMODO_DB_PASSWORD=$MONGO_PASSWORD

# ============================================================================
# Security
# ============================================================================
# Passkey for Periphery authentication
KOMODO_PASSKEY=$KOMODO_PASSKEY

# JWT secret for session tokens
KOMODO_JWT_SECRET=$KOMODO_JWT_SECRET

# Webhook secret for external integrations
KOMODO_WEBHOOK_SECRET=$KOMODO_WEBHOOK_SECRET

# ============================================================================
# Core Settings
# ============================================================================
# Host URL (set to your Tailscale hostname)
KOMODO_HOST=https://homespun:3500

# Browser title
KOMODO_TITLE=Homespun Komodo

# First server is automatically added (localhost)
KOMODO_FIRST_SERVER=https://host.docker.internal:8443

# Monitoring intervals
KOMODO_MONITORING_INTERVAL=15-sec
KOMODO_RESOURCE_POLL_INTERVAL=1-hr

# ============================================================================
# Authentication
# ============================================================================
# Enable local login
KOMODO_LOCAL_AUTH=true

# Initial admin account
KOMODO_LOCAL_AUTH_INITIAL_ADMIN_USERNAME=$ADMIN_USER
KOMODO_LOCAL_AUTH_INITIAL_ADMIN_PASSWORD=$ADMIN_PASS

# Disable signup (admin manages users)
KOMODO_DISABLE_USER_REGISTRATION=true
KOMODO_DISABLE_NON_ADMIN_CREATE=true

# ============================================================================
# Periphery Settings
# ============================================================================
PERIPHERY_ROOT_DIRECTORY=$KOMODO_DIR
PERIPHERY_PASSKEYS=$KOMODO_PASSKEY
PERIPHERY_INCLUDE_DISK_MOUNTS=/

# ============================================================================
# Timezone
# ============================================================================
TZ=UTC
EOF

sudo chmod 600 "$KOMODO_DIR/compose.env"
log_success "      Generated configuration at $KOMODO_DIR/compose.env"

# Step 5: Copy compose files
log_info "[5/5] Installing compose files..."

# Ensure config directory exists
mkdir -p "$KOMODO_CONFIG_DIR"

# Copy compose file to /etc/komodo
if [ -f "$KOMODO_CONFIG_DIR/komodo.compose.yml" ]; then
    sudo cp "$KOMODO_CONFIG_DIR/komodo.compose.yml" "$KOMODO_DIR/komodo.compose.yml"
    log_success "      Installed compose file to $KOMODO_DIR"
else
    log_error "      Compose file not found at $KOMODO_CONFIG_DIR/komodo.compose.yml"
    log_error "      Please ensure config/komodo/komodo.compose.yml exists."
    exit 1
fi

echo
log_info "======================================"
log_info "  Komodo Installation Complete"
log_info "======================================"
echo
echo "Configuration:"
echo "  Install dir:   $KOMODO_DIR"
echo "  Compose file:  $KOMODO_DIR/komodo.compose.yml"
echo "  Environment:   $KOMODO_DIR/compose.env"
echo
echo "Admin credentials:"
echo "  Username:      $ADMIN_USER"
echo "  Password:      (shown above - save it!)"
echo
echo "Next steps:"
echo "  1. Run: ./scripts/run-komodo.sh"
echo "  2. Access: https://<tailscale-hostname>:3500"
echo "  3. Log in with the admin credentials"
echo
log_success "Installation complete!"
