#!/bin/bash
set -e

# ============================================================================
# Komodo Installation Script
# ============================================================================
#
# This script installs Komodo on an Ubuntu machine with MongoDB.
# Komodo is a container management and deployment system.
#
# Usage:
#   ./scripts/install-komodo.sh
#
# Prerequisites:
#   - Docker installed and running
#   - sudo access
#
# What this script does:
#   1. Creates /etc/komodo directory structure
#   2. Downloads Komodo Docker Compose files
#   3. Generates secure secrets and environment file
#   4. Installs compose files
#
# After installation:
#   - Run ./scripts/run-komodo.sh to start Komodo
#   - Access Komodo at https://<tailscale-hostname>:3500
#
# Options:
#   --clean   Remove existing MongoDB volumes before install (fixes auth issues)
#
# Environment Variables (optional):
#   KOMODO_ADMIN_USER   - Initial admin username (default: admin)
#   KOMODO_ADMIN_PASS   - Initial admin password (auto-generated if not set)

# Colors
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log_info() { echo -e "${CYAN}$1${NC}"; }
log_success() { echo -e "${GREEN}$1${NC}"; }
log_warn() { echo -e "${YELLOW}$1${NC}"; }
log_error() { echo -e "${RED}$1${NC}"; }

# Generate a random string for secrets
generate_secret() {
    openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
}

# Default values
CLEAN_INSTALL=false

# Parse arguments
while [[ "$#" -gt 0 ]]; do
    case $1 in
        --clean) CLEAN_INSTALL=true ;;
        -h|--help)
            head -35 "$0" | tail -30
            exit 0
            ;;
        *) log_error "Unknown parameter: $1"; exit 1 ;;
    esac
    shift
done

echo
log_info "=== Komodo Installation Script ==="
echo

# Get script directory and repository root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Configuration
KOMODO_DIR="/etc/komodo"
KOMODO_CONFIG_DIR="$REPO_ROOT/config/komodo"

# Step 1: Validate Docker
log_info "[1/4] Checking prerequisites..."

if ! docker version >/dev/null 2>&1; then
    log_error "Docker is not installed or not running."
    log_error "Please install Docker: https://docs.docker.com/engine/install/ubuntu/"
    exit 1
fi
log_success "      Docker is available."

# Clean existing MongoDB volumes if requested
if [ "$CLEAN_INSTALL" = true ]; then
    log_warn "      --clean flag set: removing existing Komodo containers and MongoDB volumes..."

    # Stop existing Komodo containers
    if [ -f "$KOMODO_DIR/komodo.compose.yml" ] && [ -f "$KOMODO_DIR/compose.env" ]; then
        sudo docker compose -f "$KOMODO_DIR/komodo.compose.yml" --env-file "$KOMODO_DIR/compose.env" --profile tailscale down 2>/dev/null || true
    fi

    # Remove MongoDB volumes
    for vol in komodo_komodo-mongo-data komodo_komodo-mongo-config; do
        if docker volume inspect "$vol" >/dev/null 2>&1; then
            docker volume rm "$vol"
            log_success "      Removed volume: $vol"
        fi
    done
fi

if ! command -v openssl &>/dev/null; then
    log_error "openssl is required for secret generation."
    log_error "Install with: sudo apt-get install openssl"
    exit 1
fi
log_success "      openssl is available."

# Step 2: Create directory structure
log_info "[2/4] Creating directory structure..."

sudo mkdir -p "$KOMODO_DIR"
sudo mkdir -p "$KOMODO_DIR/backups"
sudo mkdir -p "$KOMODO_DIR/stacks"
sudo mkdir -p "$KOMODO_DIR/repos"
sudo chmod 755 "$KOMODO_DIR"

log_success "      Created $KOMODO_DIR"

# Step 3: Generate secrets and environment file
log_info "[3/4] Generating configuration..."

# Generate secrets
KOMODO_PASSKEY=$(generate_secret)
KOMODO_JWT_SECRET=$(generate_secret)
KOMODO_WEBHOOK_SECRET=$(generate_secret)
MONGO_PASSWORD=$(generate_secret)

# Admin credentials
ADMIN_USER="${KOMODO_ADMIN_USER:-admin}"
if [ -z "$KOMODO_ADMIN_PASS" ]; then
    ADMIN_PASS=$(generate_secret | head -c 16)
    log_warn "      Generated admin password: $ADMIN_PASS"
    log_warn "      Save this password! It will not be shown again."
else
    ADMIN_PASS="$KOMODO_ADMIN_PASS"
fi

# Create environment file
sudo tee "$KOMODO_DIR/compose.env" > /dev/null << EOF
# Komodo Configuration
# Generated by install-komodo.sh on $(date)

# ============================================================================
# Compose Settings
# ============================================================================
COMPOSE_KOMODO_IMAGE_TAG=latest
COMPOSE_KOMODO_BACKUPS_PATH=$KOMODO_DIR/backups

# ============================================================================
# Database Credentials
# ============================================================================
KOMODO_DB_USERNAME=komodo
KOMODO_DB_PASSWORD=$MONGO_PASSWORD

# ============================================================================
# Security
# ============================================================================
# Passkey for Periphery authentication
KOMODO_PASSKEY=$KOMODO_PASSKEY

# JWT secret for session tokens
KOMODO_JWT_SECRET=$KOMODO_JWT_SECRET

# Webhook secret for external integrations
KOMODO_WEBHOOK_SECRET=$KOMODO_WEBHOOK_SECRET

# ============================================================================
# Core Settings
# ============================================================================
# Host URL (set to your Tailscale hostname)
KOMODO_HOST=https://homespun-dev:3500

# Browser title
KOMODO_TITLE=Homespun Komodo

# First server is automatically added (periphery on Docker network)
KOMODO_FIRST_SERVER=https://homespun-komodo-periphery:8120

# Monitoring intervals
KOMODO_MONITORING_INTERVAL=15-sec
KOMODO_RESOURCE_POLL_INTERVAL=1-hr

# ============================================================================
# Authentication
# ============================================================================
# Enable local login
KOMODO_LOCAL_AUTH=true

# Initial admin account
KOMODO_INIT_ADMIN_USERNAME=$ADMIN_USER
KOMODO_INIT_ADMIN_PASSWORD=$ADMIN_PASS

# Disable signup (admin manages users)
KOMODO_DISABLE_USER_REGISTRATION=true
KOMODO_DISABLE_NON_ADMIN_CREATE=true

# ============================================================================
# Periphery Settings
# ============================================================================
PERIPHERY_ROOT_DIRECTORY=$KOMODO_DIR
PERIPHERY_PASSKEYS=$KOMODO_PASSKEY
PERIPHERY_INCLUDE_DISK_MOUNTS=/

# ============================================================================
# Tailscale
# ============================================================================
TS_HOSTNAME=homespun-dev

# ============================================================================
# Timezone
# ============================================================================
TZ=UTC
EOF

sudo chmod 600 "$KOMODO_DIR/compose.env"
log_success "      Generated configuration at $KOMODO_DIR/compose.env"

# Step 4: Copy compose files
log_info "[4/4] Installing compose files..."

# Ensure config directory exists
mkdir -p "$KOMODO_CONFIG_DIR"

# Copy compose file to /etc/komodo
if [ -f "$KOMODO_CONFIG_DIR/komodo.compose.yml" ]; then
    sudo cp "$KOMODO_CONFIG_DIR/komodo.compose.yml" "$KOMODO_DIR/komodo.compose.yml"
    log_success "      Installed compose file to $KOMODO_DIR"
else
    log_error "      Compose file not found at $KOMODO_CONFIG_DIR/komodo.compose.yml"
    log_error "      Please ensure config/komodo/komodo.compose.yml exists."
    exit 1
fi

# Verify Tailscale config exists (used by run-komodo.sh at runtime)
TAILSCALE_CONFIG_DIR="$REPO_ROOT/config/tailscale"
if [ -f "$TAILSCALE_CONFIG_DIR/start.sh" ]; then
    log_success "      Tailscale config found: $TAILSCALE_CONFIG_DIR"
else
    log_warn "      Tailscale config not found at $TAILSCALE_CONFIG_DIR"
    log_warn "      Tailscale sidecar will not be available."
fi

echo
log_info "======================================"
log_info "  Komodo Installation Complete"
log_info "======================================"
echo
echo "Configuration:"
echo "  Install dir:   $KOMODO_DIR"
echo "  Compose file:  $KOMODO_DIR/komodo.compose.yml"
echo "  Environment:   $KOMODO_DIR/compose.env"
echo
echo "Admin credentials:"
echo "  Username:      $ADMIN_USER"
echo "  Password:      (shown above - save it!)"
echo
echo "Next steps:"
echo "  1. Run: ./scripts/run-komodo.sh"
echo "  2. Access: https://<tailscale-hostname>:3500"
echo "  3. Log in with the admin credentials"
echo
log_success "Installation complete!"
