namespace Homespun.Shared.Requests;

/// <summary>
/// Request model for generating a branch ID.
/// </summary>
/// <param name="Title">The issue title to generate a branch ID from</param>
public record GenerateBranchIdRequest(string Title);

/// <summary>
/// Response model for branch ID generation.
/// </summary>
/// <param name="Success">Whether the generation succeeded</param>
/// <param name="BranchId">The generated branch ID if successful</param>
/// <param name="Error">Error message if failed</param>
/// <param name="WasAiGenerated">Whether the branch ID was generated by AI or fell back to sanitization</param>
public record GenerateBranchIdResponse(
    bool Success,
    string? BranchId,
    string? Error,
    bool WasAiGenerated);
