/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions.$sessionId'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as SessionsSessionIdIssueDiffRouteImport } from './routes/sessions.$sessionId.issue-diff'
import { Route as ProjectsProjectIdWorkflowsRouteImport } from './routes/projects.$projectId.workflows'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as ProjectsProjectIdSecretsRouteImport } from './routes/projects.$projectId.secrets'
import { Route as ProjectsProjectIdPullRequestsRouteImport } from './routes/projects.$projectId.pull-requests'
import { Route as ProjectsProjectIdPromptsRouteImport } from './routes/projects.$projectId.prompts'
import { Route as ProjectsProjectIdIssuesRouteImport } from './routes/projects.$projectId.issues'
import { Route as ProjectsProjectIdClonesRouteImport } from './routes/projects.$projectId.clones'
import { Route as ProjectsProjectIdBranchesRouteImport } from './routes/projects.$projectId.branches'
import { Route as ProjectsProjectIdWorkflowsIndexRouteImport } from './routes/projects.$projectId.workflows.index'
import { Route as ProjectsProjectIdIssuesIndexRouteImport } from './routes/projects.$projectId.issues.index'
import { Route as ProjectsProjectIdWorkflowsWorkflowIdRouteImport } from './routes/projects.$projectId.workflows.$workflowId'
import { Route as ProjectsProjectIdIssuesIssueIdEditRouteImport } from './routes/projects.$projectId.issues.$issueId.edit'
import { Route as ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRouteImport } from './routes/projects.$projectId.workflows.$workflowId.executions.$executionId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SessionsRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const SessionsSessionIdIssueDiffRoute =
  SessionsSessionIdIssueDiffRouteImport.update({
    id: '/issue-diff',
    path: '/issue-diff',
    getParentRoute: () => SessionsSessionIdRoute,
  } as any)
const ProjectsProjectIdWorkflowsRoute =
  ProjectsProjectIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSecretsRoute =
  ProjectsProjectIdSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPullRequestsRoute =
  ProjectsProjectIdPullRequestsRouteImport.update({
    id: '/pull-requests',
    path: '/pull-requests',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPromptsRoute =
  ProjectsProjectIdPromptsRouteImport.update({
    id: '/prompts',
    path: '/prompts',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdIssuesRoute = ProjectsProjectIdIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdClonesRoute = ProjectsProjectIdClonesRouteImport.update({
  id: '/clones',
  path: '/clones',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBranchesRoute =
  ProjectsProjectIdBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdWorkflowsIndexRoute =
  ProjectsProjectIdWorkflowsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdWorkflowsRoute,
  } as any)
const ProjectsProjectIdIssuesIndexRoute =
  ProjectsProjectIdIssuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdIssuesRoute,
  } as any)
const ProjectsProjectIdWorkflowsWorkflowIdRoute =
  ProjectsProjectIdWorkflowsWorkflowIdRouteImport.update({
    id: '/$workflowId',
    path: '/$workflowId',
    getParentRoute: () => ProjectsProjectIdWorkflowsRoute,
  } as any)
const ProjectsProjectIdIssuesIssueIdEditRoute =
  ProjectsProjectIdIssuesIssueIdEditRouteImport.update({
    id: '/$issueId/edit',
    path: '/$issueId/edit',
    getParentRoute: () => ProjectsProjectIdIssuesRoute,
  } as any)
const ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRoute =
  ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRouteImport.update({
    id: '/executions/$executionId',
    path: '/executions/$executionId',
    getParentRoute: () => ProjectsProjectIdWorkflowsWorkflowIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/projects/$projectId/branches': typeof ProjectsProjectIdBranchesRoute
  '/projects/$projectId/clones': typeof ProjectsProjectIdClonesRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRouteWithChildren
  '/projects/$projectId/prompts': typeof ProjectsProjectIdPromptsRoute
  '/projects/$projectId/pull-requests': typeof ProjectsProjectIdPullRequestsRoute
  '/projects/$projectId/secrets': typeof ProjectsProjectIdSecretsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/workflows': typeof ProjectsProjectIdWorkflowsRouteWithChildren
  '/sessions/$sessionId/issue-diff': typeof SessionsSessionIdIssueDiffRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/workflows/$workflowId': typeof ProjectsProjectIdWorkflowsWorkflowIdRouteWithChildren
  '/projects/$projectId/issues/': typeof ProjectsProjectIdIssuesIndexRoute
  '/projects/$projectId/workflows/': typeof ProjectsProjectIdWorkflowsIndexRoute
  '/projects/$projectId/issues/$issueId/edit': typeof ProjectsProjectIdIssuesIssueIdEditRoute
  '/projects/$projectId/workflows/$workflowId/executions/$executionId': typeof ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/settings': typeof SettingsRoute
  '/projects/new': typeof ProjectsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/projects/$projectId/branches': typeof ProjectsProjectIdBranchesRoute
  '/projects/$projectId/clones': typeof ProjectsProjectIdClonesRoute
  '/projects/$projectId/prompts': typeof ProjectsProjectIdPromptsRoute
  '/projects/$projectId/pull-requests': typeof ProjectsProjectIdPullRequestsRoute
  '/projects/$projectId/secrets': typeof ProjectsProjectIdSecretsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/sessions/$sessionId/issue-diff': typeof SessionsSessionIdIssueDiffRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/workflows/$workflowId': typeof ProjectsProjectIdWorkflowsWorkflowIdRouteWithChildren
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesIndexRoute
  '/projects/$projectId/workflows': typeof ProjectsProjectIdWorkflowsIndexRoute
  '/projects/$projectId/issues/$issueId/edit': typeof ProjectsProjectIdIssuesIssueIdEditRoute
  '/projects/$projectId/workflows/$workflowId/executions/$executionId': typeof ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prompts': typeof PromptsRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/projects/$projectId/branches': typeof ProjectsProjectIdBranchesRoute
  '/projects/$projectId/clones': typeof ProjectsProjectIdClonesRoute
  '/projects/$projectId/issues': typeof ProjectsProjectIdIssuesRouteWithChildren
  '/projects/$projectId/prompts': typeof ProjectsProjectIdPromptsRoute
  '/projects/$projectId/pull-requests': typeof ProjectsProjectIdPullRequestsRoute
  '/projects/$projectId/secrets': typeof ProjectsProjectIdSecretsRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/workflows': typeof ProjectsProjectIdWorkflowsRouteWithChildren
  '/sessions/$sessionId/issue-diff': typeof SessionsSessionIdIssueDiffRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/workflows/$workflowId': typeof ProjectsProjectIdWorkflowsWorkflowIdRouteWithChildren
  '/projects/$projectId/issues/': typeof ProjectsProjectIdIssuesIndexRoute
  '/projects/$projectId/workflows/': typeof ProjectsProjectIdWorkflowsIndexRoute
  '/projects/$projectId/issues/$issueId/edit': typeof ProjectsProjectIdIssuesIssueIdEditRoute
  '/projects/$projectId/workflows/$workflowId/executions/$executionId': typeof ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prompts'
    | '/sessions'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/new'
    | '/sessions/$sessionId'
    | '/projects/'
    | '/sessions/'
    | '/projects/$projectId/branches'
    | '/projects/$projectId/clones'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/prompts'
    | '/projects/$projectId/pull-requests'
    | '/projects/$projectId/secrets'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/workflows'
    | '/sessions/$sessionId/issue-diff'
    | '/projects/$projectId/'
    | '/projects/$projectId/workflows/$workflowId'
    | '/projects/$projectId/issues/'
    | '/projects/$projectId/workflows/'
    | '/projects/$projectId/issues/$issueId/edit'
    | '/projects/$projectId/workflows/$workflowId/executions/$executionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prompts'
    | '/settings'
    | '/projects/new'
    | '/sessions/$sessionId'
    | '/projects'
    | '/sessions'
    | '/projects/$projectId/branches'
    | '/projects/$projectId/clones'
    | '/projects/$projectId/prompts'
    | '/projects/$projectId/pull-requests'
    | '/projects/$projectId/secrets'
    | '/projects/$projectId/settings'
    | '/sessions/$sessionId/issue-diff'
    | '/projects/$projectId'
    | '/projects/$projectId/workflows/$workflowId'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/workflows'
    | '/projects/$projectId/issues/$issueId/edit'
    | '/projects/$projectId/workflows/$workflowId/executions/$executionId'
  id:
    | '__root__'
    | '/'
    | '/prompts'
    | '/sessions'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/new'
    | '/sessions/$sessionId'
    | '/projects/'
    | '/sessions/'
    | '/projects/$projectId/branches'
    | '/projects/$projectId/clones'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/prompts'
    | '/projects/$projectId/pull-requests'
    | '/projects/$projectId/secrets'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/workflows'
    | '/sessions/$sessionId/issue-diff'
    | '/projects/$projectId/'
    | '/projects/$projectId/workflows/$workflowId'
    | '/projects/$projectId/issues/'
    | '/projects/$projectId/workflows/'
    | '/projects/$projectId/issues/$issueId/edit'
    | '/projects/$projectId/workflows/$workflowId/executions/$executionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PromptsRoute: typeof PromptsRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/sessions/$sessionId/issue-diff': {
      id: '/sessions/$sessionId/issue-diff'
      path: '/issue-diff'
      fullPath: '/sessions/$sessionId/issue-diff'
      preLoaderRoute: typeof SessionsSessionIdIssueDiffRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
    '/projects/$projectId/workflows': {
      id: '/projects/$projectId/workflows'
      path: '/workflows'
      fullPath: '/projects/$projectId/workflows'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/secrets': {
      id: '/projects/$projectId/secrets'
      path: '/secrets'
      fullPath: '/projects/$projectId/secrets'
      preLoaderRoute: typeof ProjectsProjectIdSecretsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/pull-requests': {
      id: '/projects/$projectId/pull-requests'
      path: '/pull-requests'
      fullPath: '/projects/$projectId/pull-requests'
      preLoaderRoute: typeof ProjectsProjectIdPullRequestsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/prompts': {
      id: '/projects/$projectId/prompts'
      path: '/prompts'
      fullPath: '/projects/$projectId/prompts'
      preLoaderRoute: typeof ProjectsProjectIdPromptsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/issues': {
      id: '/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof ProjectsProjectIdIssuesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/clones': {
      id: '/projects/$projectId/clones'
      path: '/clones'
      fullPath: '/projects/$projectId/clones'
      preLoaderRoute: typeof ProjectsProjectIdClonesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/branches': {
      id: '/projects/$projectId/branches'
      path: '/branches'
      fullPath: '/projects/$projectId/branches'
      preLoaderRoute: typeof ProjectsProjectIdBranchesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/workflows/': {
      id: '/projects/$projectId/workflows/'
      path: '/'
      fullPath: '/projects/$projectId/workflows/'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdWorkflowsRoute
    }
    '/projects/$projectId/issues/': {
      id: '/projects/$projectId/issues/'
      path: '/'
      fullPath: '/projects/$projectId/issues/'
      preLoaderRoute: typeof ProjectsProjectIdIssuesIndexRouteImport
      parentRoute: typeof ProjectsProjectIdIssuesRoute
    }
    '/projects/$projectId/workflows/$workflowId': {
      id: '/projects/$projectId/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/projects/$projectId/workflows/$workflowId'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdRouteImport
      parentRoute: typeof ProjectsProjectIdWorkflowsRoute
    }
    '/projects/$projectId/issues/$issueId/edit': {
      id: '/projects/$projectId/issues/$issueId/edit'
      path: '/$issueId/edit'
      fullPath: '/projects/$projectId/issues/$issueId/edit'
      preLoaderRoute: typeof ProjectsProjectIdIssuesIssueIdEditRouteImport
      parentRoute: typeof ProjectsProjectIdIssuesRoute
    }
    '/projects/$projectId/workflows/$workflowId/executions/$executionId': {
      id: '/projects/$projectId/workflows/$workflowId/executions/$executionId'
      path: '/executions/$executionId'
      fullPath: '/projects/$projectId/workflows/$workflowId/executions/$executionId'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRouteImport
      parentRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdRoute
    }
  }
}

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdIssueDiffRoute: typeof SessionsSessionIdIssueDiffRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdIssueDiffRoute: SessionsSessionIdIssueDiffRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

interface SessionsRouteChildren {
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface ProjectsProjectIdIssuesRouteChildren {
  ProjectsProjectIdIssuesIndexRoute: typeof ProjectsProjectIdIssuesIndexRoute
  ProjectsProjectIdIssuesIssueIdEditRoute: typeof ProjectsProjectIdIssuesIssueIdEditRoute
}

const ProjectsProjectIdIssuesRouteChildren: ProjectsProjectIdIssuesRouteChildren =
  {
    ProjectsProjectIdIssuesIndexRoute: ProjectsProjectIdIssuesIndexRoute,
    ProjectsProjectIdIssuesIssueIdEditRoute:
      ProjectsProjectIdIssuesIssueIdEditRoute,
  }

const ProjectsProjectIdIssuesRouteWithChildren =
  ProjectsProjectIdIssuesRoute._addFileChildren(
    ProjectsProjectIdIssuesRouteChildren,
  )

interface ProjectsProjectIdWorkflowsWorkflowIdRouteChildren {
  ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRoute
}

const ProjectsProjectIdWorkflowsWorkflowIdRouteChildren: ProjectsProjectIdWorkflowsWorkflowIdRouteChildren =
  {
    ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRoute:
      ProjectsProjectIdWorkflowsWorkflowIdExecutionsExecutionIdRoute,
  }

const ProjectsProjectIdWorkflowsWorkflowIdRouteWithChildren =
  ProjectsProjectIdWorkflowsWorkflowIdRoute._addFileChildren(
    ProjectsProjectIdWorkflowsWorkflowIdRouteChildren,
  )

interface ProjectsProjectIdWorkflowsRouteChildren {
  ProjectsProjectIdWorkflowsWorkflowIdRoute: typeof ProjectsProjectIdWorkflowsWorkflowIdRouteWithChildren
  ProjectsProjectIdWorkflowsIndexRoute: typeof ProjectsProjectIdWorkflowsIndexRoute
}

const ProjectsProjectIdWorkflowsRouteChildren: ProjectsProjectIdWorkflowsRouteChildren =
  {
    ProjectsProjectIdWorkflowsWorkflowIdRoute:
      ProjectsProjectIdWorkflowsWorkflowIdRouteWithChildren,
    ProjectsProjectIdWorkflowsIndexRoute: ProjectsProjectIdWorkflowsIndexRoute,
  }

const ProjectsProjectIdWorkflowsRouteWithChildren =
  ProjectsProjectIdWorkflowsRoute._addFileChildren(
    ProjectsProjectIdWorkflowsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBranchesRoute: typeof ProjectsProjectIdBranchesRoute
  ProjectsProjectIdClonesRoute: typeof ProjectsProjectIdClonesRoute
  ProjectsProjectIdIssuesRoute: typeof ProjectsProjectIdIssuesRouteWithChildren
  ProjectsProjectIdPromptsRoute: typeof ProjectsProjectIdPromptsRoute
  ProjectsProjectIdPullRequestsRoute: typeof ProjectsProjectIdPullRequestsRoute
  ProjectsProjectIdSecretsRoute: typeof ProjectsProjectIdSecretsRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdWorkflowsRoute: typeof ProjectsProjectIdWorkflowsRouteWithChildren
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBranchesRoute: ProjectsProjectIdBranchesRoute,
  ProjectsProjectIdClonesRoute: ProjectsProjectIdClonesRoute,
  ProjectsProjectIdIssuesRoute: ProjectsProjectIdIssuesRouteWithChildren,
  ProjectsProjectIdPromptsRoute: ProjectsProjectIdPromptsRoute,
  ProjectsProjectIdPullRequestsRoute: ProjectsProjectIdPullRequestsRoute,
  ProjectsProjectIdSecretsRoute: ProjectsProjectIdSecretsRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdWorkflowsRoute: ProjectsProjectIdWorkflowsRouteWithChildren,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PromptsRoute: PromptsRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
