using System.Text.Json;
using System.Text.Json.Serialization;

namespace Homespun.Shared.Models.Sessions;

/// <summary>
/// Persistent record stored one-per-line in
/// <c>{baseDir}/{projectId}/{sessionId}.events.jsonl</c>.
///
/// <para>
/// <see cref="A2AEventRecord"/> is the on-disk representation of the raw A2A event as the
/// worker emitted it, plus the server-assigned metadata (<see cref="Seq"/>,
/// <see cref="EventId"/>, <see cref="ReceivedAt"/>) needed to replay the event verbatim.
/// The record is the server's ingestion-side contract; the downstream
/// <see cref="SessionEventEnvelope"/> wraps the translated AG-UI event the client actually
/// renders.
/// </para>
///
/// <para>
/// The A2A payload is retained as an opaque <see cref="JsonElement"/> rather than a strongly-typed
/// A2A SDK object. This keeps the store decoupled from A2A-SDK version changes and lets the
/// translator re-parse the payload lazily (and only on replay paths where it is needed).
/// </para>
/// </summary>
/// <param name="Seq">
/// Per-session monotonic sequence number starting at 1. Assigned by the store at append time.
/// </param>
/// <param name="SessionId">The Claude Code session this event belongs to.</param>
/// <param name="EventId">
/// Stable UUID generated by the server when the event is received. Persisted so that
/// replay and live broadcasts of the same event share an id the client can dedup against.
/// </param>
/// <param name="EventKind">
/// The A2A event kind string (e.g. <c>task</c>, <c>message</c>, <c>status-update</c>,
/// <c>artifact-update</c>). This is the SSE <c>event:</c> field the worker emitted and
/// is what the translator dispatches on.
/// </param>
/// <param name="ReceivedAt">UTC timestamp at which the server received the event.</param>
/// <param name="Payload">
/// The raw A2A event payload as received from the worker. Kept as a
/// <see cref="JsonElement"/> so downstream code can re-parse it into the appropriate A2A
/// SDK type without the store taking a compile-time dependency on a particular A2A schema
/// version.
/// </param>
public sealed record A2AEventRecord(
    [property: JsonPropertyName("seq")] long Seq,
    [property: JsonPropertyName("sessionId")] string SessionId,
    [property: JsonPropertyName("eventId")] string EventId,
    [property: JsonPropertyName("eventKind")] string EventKind,
    [property: JsonPropertyName("receivedAt")] DateTime ReceivedAt,
    [property: JsonPropertyName("payload")] JsonElement Payload);
